FROM golang:1.25-alpine3.22 as builder

WORKDIR /go/src/drone-email
COPY . .

RUN GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build

FROM alpine:3.22

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /go/src/drone-email/drone-email /bin/
ENTRYPOINT ["/bin/drone-email"]
